name: Deploy API to Container Apps

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master

jobs:
  buildandeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@v2.1.1
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONARCLOUD_ORGANIZATION_KEY }}
            -Dsonar.projectKey=${{ secrets.SONARCLOUD_PROJECT_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: trimSHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
            image: helloapi
            tags: prd-${{ steps.vars.outputs.sha_short }},latest
            registry: helloapiregistry.azurecr.io
            dockerfile: Dockerfile
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: helloapiregistry
          acrUsername: ${{ secrets.DOCKER_USERNAME }}
          acrPassword: ${{ secrets.DOCKER_PASSWORD }}
          containerAppName: helloapi
          containerAppEnvironment: managedEnvironment-containerhello-9670
          resourceGroup: containerhello
          imageToDeploy: helloapiregistry.azurecr.io/helloapi:prd-${{ steps.vars.outputs.sha_short }}
